Mvc5Application1/Areas/ResourceManagement/Controllers/IndividualController.cs
using Mvc5Application1.Areas.ResourceManagement.ViewModels;
using Mvc5Application1.Business.Contracts.ResourceManagement;
using Mvc5Application1.Data.Model.ResourceManagement;
using Mvc5Application1.Infrastructure.Attribute;
using Mvc5Application1.Resources;
using PagedList;
using System;
using System.Configuration;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using EmployeeBasicInfo = Mvc5Application1.Data.Model.hrm_t_employee_base;

namespace Mvc5Application1.Areas.ResourceManagement.Controllers
{
    [AllowAnonymous]
    public class IndividualController : Controller
    {
        private readonly IEmployeeBusiness _employeeBusiness;

        public IndividualController(IEmployeeBusiness employeeBusiness)
        {
            _employeeBusiness = employeeBusiness;
        }

        // GET: ResourceManagement/Individual
        public ActionResult Index()
        {
            return View();
        }

        // GET: ResourceManagement/Individual/View?id=1
        public ActionResult View(int id)
        {
            var model = _employeeBusiness.GetEmployeeDetailsById(id);
            return View(model);
        }

        // GET: ResourceManagement/Individual/Edit?id=1
        public ActionResult Edit(int id)
        {
            var model = _employeeBusiness.GetEmployeeDetailsById(id);
            return View(model);
        }

        // GET: ResourceManagement/Individual/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: ResourceManagement/Individual/Search
        public ActionResult Search()
        {
            var employeeModel = new SearchEmployeeViewModel
            {
                BirthDate = DateTime.Today.Date
            };
            return View(employeeModel);
        }

        // POST: ResourceManagement/Individual/SearchEmployee
        [HttpPost]
        public ActionResult SearchEmployee(SearchEmployeeViewModel model)
        {
            try
            {
                ViewBag.Code = model.Code;
                ViewBag.FullName = !string.IsNullOrEmpty(model.FullName) ? model.FullName.Trim() : model.FullName;
                ViewBag.FullNameEnglish = !string.IsNullOrEmpty(model.FullNameEnglish) ? model.FullNameEnglish.Trim() : model.FullNameEnglish;
                ViewBag.BirthDate = model.BirthDate;
                ViewBag.HomeTown = model.HomeTown;
                ViewBag.SortBy = "FullName";
                ViewBag.SortOrder = "asc";
                ViewBag.Page = 1;//display the first page

                var criteria = new SearchEmployeeCriteria();
                criteria.BirthDate = model.BirthDate;
                criteria.Code = model.Code;
                criteria.FullName = model.FullName;
                criteria.FullNameEnglish = model.FullNameEnglish;
                criteria.HomeTown = model.HomeTown;

                var allEmployees = _employeeBusiness.SearchEmployees(criteria);

                var allSortedEmployees = allEmployees.OrderBy(x => x.FullName);

                var pageSize = 10;

                var pageNumber = 1;

                return PartialView("_SearchEmployeeResultTable", allSortedEmployees.ToPagedList(pageNumber, pageSize));
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Success = false,
                    Message = ex.Message,
                    ReturnUrl = "/ResourceManagement/Individual/Search"
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [DisableCache]
        public ActionResult SearchEmployee(
            string code,
            string fullName,
            string fullNameEnglish,
            string homeTown,
            DateTime? birthDate,
            string sortOrder,
            string sortBy,
            int? page
            )
        {
            ViewBag.Code = !string.IsNullOrEmpty(code) ? code.Trim() : code;
            ViewBag.FullName = !string.IsNullOrEmpty(fullName) ? fullName.Trim() : fullName;
            ViewBag.FullNameEnglish = !string.IsNullOrEmpty(fullNameEnglish) ? fullNameEnglish.Trim() : fullNameEnglish;
            ViewBag.HomeTown = !string.IsNullOrEmpty(homeTown) ? homeTown.Trim() : homeTown;
            ViewBag.BirthDate = birthDate;
            ViewBag.SortBy = sortBy;
            ViewBag.SortOrder = sortOrder;
            ViewBag.Page = page;

            var viewModel = new SearchEmployeeViewModel
            {
                Code = !string.IsNullOrEmpty(code) ? code.Trim() : code,
                FullName = !string.IsNullOrEmpty(fullName) ? fullName.Trim() : fullName,
                FullNameEnglish = !string.IsNullOrEmpty(fullNameEnglish) ? fullNameEnglish.Trim() : fullNameEnglish,
                HomeTown = !string.IsNullOrEmpty(homeTown) ? homeTown.Trim() : homeTown,
                BirthDate = birthDate
            };

            var criteria = new SearchEmployeeCriteria();

            criteria.Code = viewModel.Code;
            criteria.FullName = viewModel.FullName;
            criteria.FullNameEnglish = viewModel.FullNameEnglish;
            criteria.HomeTown = viewModel.HomeTown;
            criteria.BirthDate = viewModel.BirthDate;

            var allEmployees = _employeeBusiness.SearchEmployees(criteria);

            switch (sortBy)
            {
                case "Code":
                    allEmployees = sortOrder == "desc" ? allEmployees.OrderByDescending(x => x.Code).ToList() : allEmployees.OrderBy(x => x.Code).ToList();
                    break;

                case "FullName":
                    allEmployees = sortOrder == "desc" ? allEmployees.OrderByDescending(x => x.FullName).ToList() :
                        allEmployees.OrderBy(x => x.FullName).ToList();
                    break;

                case "FullNameEnglish":
                    allEmployees = sortOrder == "desc" ? allEmployees.OrderByDescending(x => x.FullNameEnglish).ToList() :
                        allEmployees.OrderBy(x => x.FullNameEnglish).ToList();
                    break;

                case "HomeTown":
                    allEmployees = sortOrder == "desc" ? allEmployees.OrderByDescending(x => x.HomeTown).ToList() : allEmployees.OrderBy(x => x.HomeTown).ToList();
                    break;

                case "BirthDate":
                    allEmployees = sortOrder == "desc" ? allEmployees.OrderByDescending(x => x.BirthDate).ToList() : allEmployees.OrderBy(x => x.BirthDate).ToList();
                    break;

                default:
                    allEmployees = sortOrder == "desc" ? allEmployees.OrderByDescending(x => x.FullName).ToList() :
                        allEmployees.OrderBy(x => x.FullName).ToList();
                    break;
            }

            var pageSize = 10;

            var pageNumber = (page ?? 1);

            return PartialView("_SearchEmployeeResultTable", allEmployees.ToPagedList(pageNumber, pageSize));
        }

        // POST: ResourceManagement/Individual/SaveBasicInformation

        [HttpPost]
        [ValidateAntiForgeryToken()]
        public ActionResult SaveBasicInformation(EmployeeBasicInfo model)
        {
            if (ModelState.IsValid)
            {
                #region Save file to temporary folder

                var fileName = string.Empty;
                var logicalName = string.Empty;
                var file = Request.Files["fileImport"];
                var fileSize = Convert.ToInt32(ConfigurationManager.AppSettings["MaxFileSize"].ToString()); // Max file size is 10485760
                if (file != null && file.ContentLength > 0)
                {
                    if (file.ContentLength > fileSize)
                    {
                        return Json(new { message = string.Format("Max file size is {0}, please input other image file.", fileSize) }, JsonRequestBehavior.AllowGet);
                    }

                    var extension = Path.GetExtension(file.FileName);
                    if (extension != ".png" && extension != ".jpg" && extension != ".jpeg" && extension != ".gif" && extension != ".tif")
                    {
                        return Json(new { message = "File type is an image, please input other image file." }, JsonRequestBehavior.AllowGet);
                    }

                    var fileNameNoEx = Path.GetFileNameWithoutExtension(file.FileName);
                    var timeStamp = DateTime.Now.ToString("yyyyMMddHHmmssfff");
                    fileName = string.Concat(fileNameNoEx, timeStamp, extension);
                    logicalName = string.Concat(fileNameNoEx, extension);
                    string uploadPath = ConfigurationManager.AppSettings["ImportUploadFilePath"].ToString();
                    bool exists = Directory.Exists(Server.MapPath(uploadPath));
                    if (!exists)
                        Directory.CreateDirectory(Server.MapPath(uploadPath));

                    var path = Path.Combine(Server.MapPath(uploadPath), fileName);
                    file.SaveAs(path);
                }

                #endregion Save file to temporary folder

                var employee = new EmployeeBasicInfo();
                employee.maiden_name = model.maiden_name;
                employee.maiden_name_eng = model.maiden_name_eng;
                employee.sex_div = model.sex_div;
                employee.blood_type_div = model.blood_type_div;
                employee.hometown_name = model.hometown_name;
                employee.birth_date = model.birth_date;

                employee.image_file_logical_name = logicalName;
                employee.image_file_physical_name = fileName;

                _employeeBusiness.SaveEmployee(employee);

                return Json(new
                {
                    Success = true,
                    Message = "Redirecting...",

Mvc5Application1/Areas/ResourceManagement/Views/Individual/Create.cshtml
@model Mvc5Application1.Data.Model.hrm_t_employee_base

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_LoadingPartial")

@using (Html.BeginForm("SaveBasicInformation", "Individual", FormMethod.Post, new { @id = "formBasicInformation", @novalidate = "", @class = "form-horizontal form-label-left" }))
{
    @Html.AntiForgeryToken()
    <span class="section">Cơ bản</span>
    <!-- fullName -->
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fullName">
            Họ tên <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="fullName" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2"
                   name="fullName" placeholder="e.g Nguyễn Văn An" required="required" type="text">
        </div>
    </div>
    <!-- /fullName -->
    <!-- fullNameEnglish -->
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fullNameEnglish">
            Họ tên (tiếng Anh)
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="fullNameEnglish" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2"
                   name="fullNameEnglish" placeholder="e.g Jon Doe" type="text">
        </div>
    </div>
    <!-- /fullNameEnglish -->
    <!-- gender -->
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="gender">
            Giới tính
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <select class="form-control" id="gender" name="gender">
                <option>Male</option>
                <option>Female</option>
            </select>
        </div>
    </div>
    <!-- /gender -->
    <!-- bloodGroup -->
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="bloodGroup">
            Nhóm máu
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <select class="form-control" id="bloodGroup" name="bloodGroup">
                <option>Unknow</option>
                <option>A</option>
                <option>B</option>
                <option>O</option>
                <option>AB</option>
            </select>
        </div>
    </div>
    <!-- /bloodGroup -->
    <!-- homeTown -->
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="homeTown">
            Quê quán
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <textarea id="homeTown" class="form-control"
                      name="homeTown" data-parsley-trigger="keyup" data-parsley-minlength="20" data-parsley-maxlength="100" data-parsley-minlength-message="Come on! You need to enter at least a 20 caracters long comment.." data-parsley-validation-threshold="10"></textarea>
        </div>
    </div>
    <!-- /homeTown -->
    <!-- dateOfBirth -->
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12">
            Ngày sinh
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="dateOfBirth" name="dateOfBirth" class="datepicker form-control col-md-7 col-xs-12 active" type="text">
        </div>
    </div>
    <!-- /dateOfBirth -->
    <!-- Avatar -->
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12">
            Ảnh đại diện
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="btn-group">
                <label class="btn btn-primary btn-upload" for="fileImport" title="Upload image file">
                    <input class="sr-only" id="fileImport" name="fileImport" accept="image/*" type="file">
                    <span class="docs-tooltip" data-toggle="tooltip" title="" data-original-title="Import image with Blob URLs">
                        <span class="fa fa-upload"></span>
                    </span>
                </label>
            </div>
        </div>
    </div>
    <!-- /Avatar -->
    <!-- HR -->
    <div class="ln_solid"></div>
    <!-- /HR -->
    <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
            <button type="reset" class="btn btn-primary">Thiết lập lại</button>
            <button id="submitBtn" type="submit" class="btn btn-success">Thêm mới</button>
        </div>
    </div>
}

<script>
    $(function () {
        var date = new Date();
        var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        var end = new Date(date.getFullYear(), date.getMonth(), date.getDate());

        $('#dateOfBirth').datepicker({ format: "dd/mm/yyyy", autoclose: true });

        $('#dateOfBirth').datepicker('setDate', today);
    });

    $(function () {
        $(document).on("click", "#submitBtn", function (e) {
            e.preventDefault();
            //window.alert('hello');

            // Reset notification
            //$('#notification-bar').text('');

            var urlAction = $('#formBasicInformation').attr("action");

            var formData = new FormData();

            // Add value from Html.AntiForgeryToken()
            var formDataArray = $('#formBasicInformation').serializeArray();
            for (var i = 0; i < formDataArray.length; i++) {
                var formDataItem = formDataArray[i];
                console.log(formDataItem);
                formData.append(formDataItem.name, formDataItem.value);
            }

            formData.append("maiden_name", $('#fullName').val());
            formData.append("maiden_name_eng", $('#fullNameEnglish').val());
            formData.append("sex_div", $('#gender').val());
            formData.append("blood_type_div", $('#bloodGroup').val());
            formData.append("hometown_name", $('#homeTown').val());
            formData.append("birth_date", $('#dateOfBirth').val());

            // Avatar
            var file = document.getElementById("fileImport").files[0];
            formData.append("fileImport", file);

            $("#submitBtn").prop("disabled", true); // Before send AJAX request

            //debugger;

            $.ajax({
                type: "POST",
                url: urlAction,
                data: formData,
                processData: false,
                contentType: false,
                beforeSend: function () {
                    //debugger;
                    $("#divProcessing").show();
                },
                complete: function () {
                    //debugger;
                    $("#divProcessing").hide();
                    $("#submitBtn").prop("disabled", false); // After send AJAX request
                },
                success: function (result) {
                    //debugger;
                    if (!result.Success) {
                        //$('#notification-bar').text('Save successfully');
                        $("#notification-bar").text(result.Message);

                        $("#fullName").focus();
                        $("#fullName").select();
                    }
                    else {
                        //window.location.replace(result.ReturnUrl);
                        window.location.href = result.ReturnUrl;
                    }
                },
                error: function (xhr, status, error) {
                    //debugger;
                    //$('#notification-bar').text('An error occurred');
                }
            });
        });
    });
</script>

Mvc5Application1/Areas/ResourceManagement/Views/Individual/Edit.cshtml
@using Mvc5Application1.Data.Model
@model hrm_t_employee_base

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("SaveBasicInformation", "Individual", FormMethod.Post, new { @id = "formBasicInformation", @novalidate = "", @class = "form-horizontal form-label-left" }))
{
    @Html.AntiForgeryToken()
    <span class="section">Cơ bản</span>
    <!-- fullName -->
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fullName">
            Họ tên <span class="required">*</span>
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input value="@Model.maiden_name" id="fullName" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2"
                   name="fullName" placeholder="e.g Nguyễn Văn An" required="required" type="text">
        </div>
    </div>
    <!-- /fullName -->
    <!-- fullNameEnglish -->
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fullNameEnglish">
            Họ tên (tiếng Anh)
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input value="@Model.maiden_name_eng" id="fullNameEnglish" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2"
                   name="fullNameEnglish" placeholder="e.g Jon Doe" type="text">
        </div>
    </div>
    <!-- /fullNameEnglish -->
    <!-- gender -->
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="gender">
            Giới tính
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <select class="form-control" id="gender" name="gender" gender="@Model.sex_div">
                <option>Male</option>
                <option>Female</option>
            </select>
        </div>
    </div>
    <!-- /gender -->
    <!-- bloodGroup -->
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="bloodGroup">
            Nhóm máu
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <select class="form-control" id="bloodGroup" name="bloodGroup" bloodgroup="@Model.blood_type_div">
                <option>Unknow</option>
                <option>A</option>
                <option>B</option>
                <option>O</option>
                <option>AB</option>
            </select>
        </div>
    </div>
    <!-- /bloodGroup -->
    <!-- homeTown -->
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="homeTown">
            Quê quán
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <textarea id="homeTown" class="form-control" name="homeTown" data-parsley-trigger="keyup" data-parsley-minlength="20" data-parsley-maxlength="100" data-parsley-minlength-message="Come on! You need to enter at least a 20 caracters long comment.." data-parsley-validation-threshold="10">@Model.hometown_name</textarea>
        </div>
    </div>
    <!-- /homeTown -->
    <!-- dateOfBirth -->
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12">
            Ngày sinh
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input value="@Model.birth_date.Value.ToString(CommonString.DateFormat)" id="dateOfBirth" name="dateOfBirth" class="datepicker form-control col-md-7 col-xs-12 active" type="text">
        </div>
    </div>
    <!-- /dateOfBirth -->
    <!-- Avatar -->
    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12">
            Ảnh đại diện
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="btn-group">
                <label class="btn btn-primary btn-upload" for="fileImport" title="Upload image file">
                    <input class="sr-only" id="fileImport" name="fileImport" accept="image/*" type="file">
                    <span class="docs-tooltip" data-toggle="tooltip" title="" data-original-title="Import image with Blob URLs">
                        <span class="fa fa-upload"></span>
                    </span>
                </label>
            </div>
        </div>
    </div>
    <!-- /Avatar -->
    <!-- HR -->
    <div class="ln_solid"></div>
    <!-- /HR -->
    <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
            <button type="reset" class="btn btn-primary">Thiết lập lại</button>
            <button id="submitBtn" type="submit" class="btn btn-success">Cập nhật</button>
        </div>
    </div>
}

<script>

    $(window).on("load", function () {
        var bloodgroup = $('#bloodGroup').attr("bloodgroup");
        var gender = $('#gender').attr("gender");
        $('select[name="gender"]').val(gender);
        $('select[name="bloodGroup"]').val(bloodgroup);
    });

    $(function () {
        var date = new Date();
        var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        var end = new Date(date.getFullYear(), date.getMonth(), date.getDate());

        $('#dateOfBirth').datepicker({ format: "dd/mm/yyyy", autoclose: true });

        $('#dateOfBirth').datepicker('setDate', today);
    });

    $(function () {
        $(document).on("click", "#submitBtn", function (e) {
            e.preventDefault();
            //window.alert('hello');

            // Reset notification
            //$('#notification-bar').text('');

            var urlAction = $('#formBasicInformation').attr("action");

            var formData = new FormData();

            // Add value from Html.AntiForgeryToken()
            var formDataArray = $('#formBasicInformation').serializeArray();
            for (var i = 0; i < formDataArray.length; i++) {
                var formDataItem = formDataArray[i];
                console.log(formDataItem);
                formData.append(formDataItem.name, formDataItem.value);
            }

            formData.append("maiden_name", $('#fullName').val());
            formData.append("maiden_name_eng", $('#fullNameEnglish').val());
            formData.append("sex_div", $('#gender').val());
            formData.append("blood_type_div", $('#bloodGroup').val());
            formData.append("hometown_name", $('#homeTown').val());
            formData.append("birth_date", $('#dateOfBirth').val());

            // Avatar
            var file = document.getElementById("fileImport").files[0];
            formData.append("fileImport", file);

            $("#submitBtn").prop("disabled", true); // Before send AJAX request

            //debugger;

            $.ajax({
                type: "POST",
                url: urlAction,
                data: formData,
                processData: false,
                contentType: false,
                beforeSend: function () {
                    //debugger;
                    $("#divProcessing").show();
                },
                complete: function () {
                    //debugger;
                    $("#divProcessing").hide();
                    $("#submitBtn").prop("disabled", false); // After send AJAX request
                },
                success: function (result) {
                    //debugger;
                    if (!result.Success) {
                        //$('#notification-bar').text('Save successfully');
                        $("#notification-bar").text(result.Message);

                        $("#fullName").focus();
                        $("#fullName").select();
                    }
                    else {
                        //window.location.replace(result.ReturnUrl);
                        window.location.href = result.ReturnUrl;
                    }
                },
                error: function (xhr, status, error) {
                    //debugger;
                    //$('#notification-bar').text('An error occurred');
                }
            });
        });
    });
</script>

Mvc5Application1/Areas/ResourceManagement/Views/Individual/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Mvc5Application1/Areas/ResourceManagement/Views/Individual/Search.cshtml
@model Mvc5Application1.Areas.ResourceManagement.ViewModels.SearchEmployeeViewModel

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/Employee/EmployeeScript.js"></script>

@Html.Partial("_LoadingPartial")

<form id="searchEmployeeForm" method="POST" class="form-horizontal">
    <span class="section">Tìm kiếm nhân viên</span>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="code">
            Mã nhân viên
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="code" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2"
                   name="code" placeholder="" type="text">
        </div>
    </div>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fullName">
            Họ tên
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="fullName" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2"
                   name="fullName" placeholder="" type="text">
        </div>
    </div>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="fullNameEnglish">
            Họ tên (Tiếng Anh)
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="fullNameEnglish" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2"
                   name="fullNameEnglish" placeholder="" type="text">
        </div>
    </div>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="homeTown">
            Quê quán
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input id="homeTown" class="form-control col-md-7 col-xs-12" data-validate-length-range="6" data-validate-words="2"
                   name="homeTown" placeholder="" type="text">
        </div>
    </div>
    <div class="item form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="birthDate">
            Ngày sinh
        </label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="input-group date">
                <input type="text" class="datepicker form-control col-md-7 col-xs-12 active" id="birthDate" name="birthDate">
                <div class="input-group-addon">
                    <span class="glyphicon glyphicon-th"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 form-group has-feedback col-md-offset-3">
        <button id="btnSearchEmployee" type="submit" class="btn btn-primary">Tìm kiếm</button>
        <button id="btnAddEmployee" class="btn btn-primary">Thêm mới</button>
    </div>
</form>
<span class="section">Kết quả tìm kiếm</span>
<div id="employee-result-message"></div>
<div id="EmployeeResultTable">
</div>

<script type="text/javascript">

    $(function () {
        var date = new Date();
        var today = new Date(date.getFullYear(), date.getMonth(), date.getDate());
        var end = new Date(date.getFullYear(), date.getMonth(), date.getDate());

        $('#birthDate').datepicker({ format: "dd/mm/yyyy", autoclose: true });

        $('#birthDate').datepicker('setDate', today);
    });

    $(document).ready(function () {

        $.validator.unobtrusive.parse($('#searchEmployeeForm'));

        $('#searchEmployeeForm').on('submit', function (evt) {

            evt.preventDefault();

            $('#btnSearchEmployee').prop("disabled", true);

            if (!$('#searchEmployeeForm').valid()) {
                $('#btnSearchEmployee').prop("disabled", false);
                return;
            }

            $("#divProcessing").show();

            $.ajax({
                async: true,
                url: '@Url.Action("SearchEmployee", "Individual", new { area = "ResourceManagement" })',
                type: "POST",
                data: $(this).serialize(),
                success: function (result) {
                    //debugger;
                    $('#btnSearchEmployee').prop("disabled", false);
                    $("#divProcessing").hide();
                    if (result.Success == null) {
                        //debugger;
                        $('#employee-result-message').hide();
                        $('#EmployeeResultTable').html(result); // assuming response is HTML
                    } else {
                        //debugger;
                        if (!result.Success) {
                            //debugger;
                            $('#employee-result-message').show();
                            $('#employee-result-message').html(result.Message);
                        }
                    }
                },
                error: function (xhr, status, error) {
                    //debugger;
                    $('#btnSearchEmployee').prop("disabled", false);
                    $("#divProcessing").hide();
                }
            });
        });
    });
</script>

<script type="text/javascript">

    $(function () {
        $(document).on("click", "#btnAddEmployee", function () {
            window.location.href = '/ResourceManagement/Individual/Create';
        });
    });

    $(document).ready(function () {
        $("#employee-results tbody tr td").on('click', 'a[class="delete-item"]', function (evt) {
            evt.preventDefault();
            var itemid = $(this).attr('itemid');
            $('#btnDeleteItem').attr('itemid', itemid);
            $('#btnDeleteItem').click();
        });
    });
</script>